version: "3.9"

services:
  bankbranches:
    build:
      context: ./bankbranches
      dockerfile: ./Dockerfile
    ports:
      - "7001:7001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bankbranches
    depends_on:
      - mongo

  bankbranchreviews:
    build:
      context: ./bankbranchreviews
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"

  bankclient:
    build:
      context: ./bankclient
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
